### ISSUE TITLE
Docker : repository name must be lowercase 

### ISSUE THREAD

**Issue by MehdiABM** [aksub99/MolDQN-pytorch#8]
Hello, 

Thanks for sharing your source code, and for the amazing work.

When running the docker build command in the README, I get the following error :
`invalid argument "MolDQN_pytorch:latest" for "-t, --tag" flag: invalid reference format: repository name must be lowercase`

I guess the image name may be required to be lowercase.

Thanks again,

**Comment by aksub99** [comment]
Hi @MehdiABM , you're right. The image name must indeed be lowercase.
Thanks for letting me know:)
`
The following should work:
```
# Build the Dockerfile in Dockerfiles/Dockerfile to create a Docker image.

cd Dockerfiles
docker build -t moldqn_pytorch:latest .

# This will create a container from the image we just created.
nvidia-docker run -[Options] moldqn_pytorch:latest python path/to/main.py

```
I'll update the README with this information.

**Comment by aksub99** [comment]
Just updated the README. 
Please note that the `nvidia-docker run` command was also slightly flawed in the old version of the README. The current installation instructions should work.

**Comment by MehdiABM** [comment]
Thanks a lot :)
